In [3]:
import numpy as np

# Create arrays from lists
arr1 = np.array([1, 2, 3, 4])  # 1D array
arr2 = np.array([[1, 2], [3, 4]])  # 2D array

# Generating Arrays
zeros = np.zeros((3, 3))  # 3x3 array of zeros
ones = np.ones((2, 4))  # 2x4 array of ones
range_arr = np.arange(0, 10, 2)  # Array from 0 to 10 with step 2
linspace = np.linspace(0, 1, 5)  # 5 evenly spaced numbers between 0 and 1
random_arr = np.random.rand(3, 3)  # 3x3 array of random numbers

In [2]:
# Element-wise operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Add arrays
c = a + b  # [5, 7, 9]

# Multiply arrays
d = a * b  # [4, 10, 18]

# Scalar operations
e = a * 2  # [2, 4, 6]

# Square root
sqrt_a = np.sqrt(a)  # [1.0, 1.414, 1.732]

# Exponentiation
exp_a = np.exp(a)  # [2.718, 7.39, 20.09]

# Power
power_a = np.power(a, 2)  # [1, 4, 9]

# Broadcasting
matrix = np.array([[1, 2, 3], [4, 5, 6]])
scalar_add = matrix + 10  # Add 10 to every element

#print an example
print(a)
print(b)
print(c)
print(d)
print(e)
print("Square root", sqrt_a)
print("Exponentiation", exp_a)
print("Power", power_a)
print("Broadcasting\n", scalar_add)

[1 2 3]
[4 5 6]
[5 7 9]
[ 4 10 18]
[2 4 6]
Square root [1.         1.41421356 1.73205081]
Exponentiation [ 2.71828183  7.3890561  20.08553692]
Power [1 4 9]
Broadcasting
 [[11 12 13]
 [14 15 16]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Basic statistics
mean = np.mean(arr)  # Average
median = np.median(arr)
std_dev = np.std(arr)  # Standard deviation
min_val = np.min(arr)
max_val = np.max(arr)

# Mathematical transformations
squared = np.square(arr)
square_root = np.sqrt(arr)
exponential = np.exp(arr)
logarithm = np.log(arr)

# Trigonometric functions
sin_arr = np.sin(arr)
cos_arr = np.cos(arr)

In [10]:
# Reshaping arrays
arr = np.arange(12)
reshaped = arr.reshape((3, 4))  # 3 rows, 4 columns MUST be compatible with original size, ex 3*4=12 or 4*3=12 or 2*6=12
print("Original array:\n", arr)
print("Reshaped array:\n", reshaped)
# Slicing
first_row = reshaped[0, :]  # First row
first_column = reshaped[:, 0]  # First column
print("First row:\n", first_row)
print("First column:\n", first_column)
# Conditional selection
filtered = arr[arr > 5]  # Elements greater than 5
print("Filtered array:\n", filtered)

Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
First row:
 [0 1 2 3]
First column:
 [0 4 8]
Filtered array:
 [ 6  7  8  9 10 11]


In [12]:
# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Dot product
dot_product = np.dot(A, B)
print("Dot product:\n", dot_product)
# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)
# Solving linear equations
x = np.linalg.solve(A, B)
print("Solution to linear equations:\n", x)

Dot product:
 [[19 22]
 [43 50]]
Eigenvalues:
 [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Solution to linear equations:
 [[-3. -4.]
 [ 4.  5.]]


In [ ]:
# Generating random numbers
normal_dist = np.random.normal(0, 1, (3, 3))  # Mean 0, std 1
uniform_dist = np.random.uniform(0, 1, (3, 3))

# Random sampling
random_choice = np.random.choice([1, 2, 3, 4], size=(2, 3))

In [11]:
help(np.sum)

Help on _ArrayFunctionDispatcher in module numpy:

sum(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>
)
    Sum of array elements over a given axis.

    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis. If
        axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In that