Mi intento de aprender indexing y slicing

In [3]:
import numpy as np
#Primero tengamos una matriz de 4x4
A = [[1,  2,  3,  10], 
     [4,  5,  6,  11], 
     [7,  8,  9,  12],
     [13, 14, 15, 16]]
# Para que sea más util, la convertimos a un array de numpy
A = np.array(A)

In [ ]:
#Ahora vamos a intentar cositas con indexing

print("Primera Fila: ",A[0]) #Esto nos da la primera fila de la matriz
print("Primera Fila2: ",A[0, :]) #Esto nos da la primera fila de la matriz
print("Primera Columna: ",A[:, 0]) #Esto nos da la primera columna de la matriz

#más dificil sería obtener submatrices
print("Submatriz esquina superior isquierda: \n", A[0:2, 0:2]) #Esto nos da la submatriz de la esquina superior izquierda
print("Otra submatriz: \n",A[1:3, 1:3]) #Esto nos da la submatriz de la esquina inferior derecha
print("Otra submatriz: \n", A[:,:3])

#Podemos obtener la diagonal de la matriz con np.diag
print("Diagonal: ",np.diag(A)) #Esto nos da la diagonal de la matriz
#Podemos obtener la transpuesta de la matriz con np.transpose
print("Transpuesta: \n",np.transpose(A))

Primera Fila:  [ 1  2  3 10]
Primera Fila2:  [ 1  2  3 10]
Primera Columna:  [ 1  4  7 13]
Submatriz esquina superior isquierda: 
 [[1 2]
 [4 5]]
Otra submatriz: 
 [[5 6]
 [8 9]]
Otra submatriz: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [13 14 15]]
Diagonal:  [ 1  5  9 16]
Transpuesta:  [[ 1  4  7 13]
 [ 2  5  8 14]
 [ 3  6  9 15]
 [10 11 12 16]]


In [ ]:
#Cambiando a un modo más complejo de verlo.

# Intentemos recordar lo que era usar el : en listas
# si tengo [1:] sería todo lo que está a la derecha del primer elemento
# Si quiero hacerlo con la matriz, tengo que sacar alguna fila (obtengo lista) y hago la operación
A[1,1:]



array([ 5,  6, 11])

In [20]:
# Algo aún más complejo es steps.
# es de este formato:
# start:stop:step
# Comienza en start, se detiene en stop y avanza en step pasos.
# Por ejemplo, con la matriz A, quiero ver una submatriz a base de los elementos pares. (fila y columnas pares)
A[::2,::2]

array([[1, 3],
       [7, 9]])

In [21]:
#otro ejemplo
A[::2,:]

array([[ 1,  2,  3, 10],
       [ 7,  8,  9, 12]])

In [27]:
#Más practica.
#nueva matriz
A = np.arange(20).reshape(4,5)
print(A)
#Extraer subarray central
A[1:3,1:4]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([[ 6,  7,  8],
       [11, 12, 13]])

In [ ]:
# Invertir el orden de las filas
A[::-1,:]

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [18]:
# Invertir el orden de las columnas
A[:,::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15]])

In [19]:
# Invertir el orden de las filas y columnas
A[::-1,::-1]

array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [20]:
# Extraer todas las filas pares
A[::2,]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [22]:
# Extraer las columnas impares
A[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19]])

In [24]:
A[(A > 10)]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
A[(A %3 == 0)] = -1
print(A)

[[-1  1  2 -1  4]
 [ 5 -1  7  8 -1]
 [10 11 -1 13 14]
 [-1 16 17 -1 19]]


In [28]:
A[1::2,] = 0
print(A)

[[ 0  1  2  3  4]
 [ 0  0  0  0  0]
 [10 11 12 13 14]
 [ 0  0  0  0  0]]


In [29]:
B = np.arange(24).reshape(2,3,4)
print(B)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [30]:
B[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [32]:
B[:,1,]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [33]:
B[:,:,-1]

array([[ 3,  7, 11],
       [15, 19, 23]])

In [34]:
B[:,:,::-1]

array([[[ 3,  2,  1,  0],
        [ 7,  6,  5,  4],
        [11, 10,  9,  8]],

       [[15, 14, 13, 12],
        [19, 18, 17, 16],
        [23, 22, 21, 20]]])

In [35]:
B[(B > 15)]

array([16, 17, 18, 19, 20, 21, 22, 23])

In [16]:
C = np.arange(1.,26.).reshape(5,5)
print(C)
np.diag(C[::1,::-1])

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]


array([ 5.,  9., 13., 17., 21.])

In [17]:
D= np.diag(C)
D**-1

array([1.        , 0.14285714, 0.07692308, 0.05263158, 0.04      ])